version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata_prod:/var/lib/postgresql/data

  backend:
    build: ./backend
    image: backend-prod
    container_name: backend-prod
    environment:
      - ENV_PREFIX=/prod
      - PORT=4001
    ports:
      - "4001:4001"
    depends_on:
      - db

  frontend:
    build: ./frontend
    image: frontend-prod
    container_name: frontend-prod
    environment:
      - VITE_BASE_PATH=/prod/
    ports:
      - "5174:4173"
    depends_on:
      - backend

volumes:
  pgdata_prod:

