name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Run tests
        run: |
          cd backend
          npm test -- --coverage

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: backend/coverage

  deploy-homolog:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Deploy to Homolog
        uses: appleboy/ssh-action@master
        with:
          host: 177.44.248.77
          username: univates
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/pipeline-gerencia
            git pull origin main
            docker-compose -f docker-compose.homolog.yml up -d --build

  deploy-prod:
    if: github.event.head_commit.message == 'deploy:prod'
    runs-on: ubuntu-latest
    needs: deploy-homolog
    steps:
      - name: Deploy to Prod
        uses: appleboy/ssh-action@master
        with:
          host: 177.44.248.77
          username: univates
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/pipeline-gerencia
            git pull origin main
            docker-compose -f docker-compose.prod.yml up -d --build
